SET SERVEROUTPUT ON;

DECLARE TYPE DATOS IS RECORD(
nombre VARCHAR2(100),
pass varchar2(20)
);
DATO1 DATOS;
BEGIN
    
    SELECT NAME,PASSWORD INTO DATO1.nombre,DATO1.pass FROM TEST;
    DBMS_OUTPUT.PUT_LINE(DATO1.nombre||'    '||DATO1.pass);
    EXCEPTION
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('mas de un registro involucrado');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('INTERESANTE no hubo ningun dato');
END;
commit;

--INSERT Y UPDATE CON RECORDS Y COLECCIONES
/
SET SERVEROUTPUT ON;
DECLARE FILA TEST%ROWTYPE;
BEGIN
FILA.USER_ID:=7;
FILA.NAME:='ANGIE';
FILA.PASSWORD:='74899773';

INSERT INTO TEST VALUES FILA;
EXCEPTION 
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE("Error desconocido");

END;
/
SELECT * FROM TEST;
/
SET SERVEROUTPUT ON;
---ARRAYS ASOCIATIVOS
DECLARE TYPE DATOS IS TABLE OF
        TEST%ROWTYPE;
        DATA1 DATOS;
BEGIN

FOR I IN 1..10 LOOP
    SELECT * INTO DATA1(I) FROM TEST where USER_ID=I;
END LOOP;

FOR I IN DATA1.FIRST.. DATA1.LAST LOOP
    DBMS_OUTPUT.PUT_LINE(DATA1(I).name);
END LOOP;


EXCEPTION 
    WHEN NO_DATA_FOUND THEN
    NULL;
    WHEN TOO_MANY_ROWS THEN
    NULL;
    WHEN OTHERS THEN
    NULL;
DBMS_OUTPUT.PUT_LINE("Ya no continua");
END;