--CREACION DE EXCEPCIONES
SET SERVEROUTPUT ON;
DECLARE TABLA TEST%ROWTYPE;
     MY_EXCEP EXCEPTION;
    PRAGMA EXCEPTION_INIT(MY_EXCEP,-937);
BEGIN
    SELECT * INTO TABLA FROM TEST WHERE NAME LIKE '%ANN%';
    DBMS_OUTPUT.PUT_LINE(TABLA.NAME);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
          DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO UN VALOR PARA ESE REGISTRO');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('MAS DE UN REGISTRO ENCONTRADO');--*/
        WHEN MY_EXCEP THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE EXCEPTION');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

--EXPECIONES PERSONALIZADAS
SET SERVEROUTPUT ON;
DECLARE ERROR1 EXCEPTION;
        A NUMBER:=9;
BEGIN
    IF A>5 THEN
        RAISE ERROR1;
    ELSE 
        A:=A-1;
    END IF;
    
    EXCEPTION
        WHEN ERROR1 THEN
            DBMS_OUTPUT.PUT_LINE('ERROR INTERESANTE');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR DESCONOCIDO');
END;

/
--TAMBIEN TENEMOS AL RAISE_APLICATION_ERROR()

