--Fiunciones bassicas de SQL
--lA MAYORIA DE LAS FUNCIONES SERAN EXPLICADAS EN BREVEDAD
SET SERVEROUTPUT ON;
DECLARE V VARCHAR2(100);
BEGIN
    DBMS_OUTPUT.PUT_LINE(ISNULL(V,'sin valor asignado'));
END;
