CREATE OR REPLACE FUNCTION nUsuarios
RETURN NUMBER
AS
N NUMBER:=0;
BEGIN
SELECT COUNT(*) INTO N FROM TEST;
RETURN N;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    N:=0;
    RETURN N;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error grave encontrado '||SQLCODE||' ERROR: '||SQLERRM);
END nUsuarios;
/
SET SERVEROUTPUT ON;
DECLARE NU NUMBER;
BEGIN
    NU:=NUSUARIOS();
    DBMS_OUTPUT.PUT_LINE(NU);
END;