SET SERVEROUTPUT ON;

DECLARE
    EMPLEADO EMPLOYEES%ROWTYPE;
    APELLIDO EMPLOYEES.LAST_NAME%TYPE;
BEGIN
    SELECT * INTO EMPLEADO
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID=200;
    DBMS_OUTPUT.PUT_LINE(EMPLEADO.FIRST_NAME);
    
    SELECT LAST_NAME INTO APELLIDO
            FROM EMPLOYEES
            WHERE EMPLOYEE_ID=200;
    DBMS_OUTPUT.PUT_LINE(APELLIDO);
END;

DECLARE ID_USER NUMBER;
        NOMBRE TEST.NAME%TYPE;
        PASS TEST.PASSWORD%TYPE; 

BEGIN
    ID_USER:=1;
    NOMBRE:='AMPARO.PAEZ';
    PASS:='34567732';
INSERT INTO TEST (USER_ID,NAME,PASSWORD) VALUES (2,'amparo.paez',PASS);
END;
UPDATE TEST SET USER_ID=3 WHERE NAME='JOHAN.MITMA';

END;
/
SET SERVEROUTPUT ON;
DECLARE NOMBRE test.name%type;
BEGIN
SELECT NAME INTO NOMBRE FROM TEST WHERE USER_ID=3;
DBMS_OUTPUT.PUT_LINE(NOMBRE);
END;
/



